"""them moi quan he

Revision ID: 2ab47fa9de2a
Revises: 6a632741b062
Create Date: 2025-04-18 00:05:50.647604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ab47fa9de2a'
down_revision: Union[str, None] = '6a632741b062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('profile_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'images', 'profiles', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'profile_id')
    # ### end Alembic commands ###
