"""init schema

Revision ID: a8758c630038
Revises: 
Create Date: 2025-04-17 16:29:46.902369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8758c630038'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    op.drop_table('demo-table')
    op.add_column('profiles', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('profiles', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('profiles', sa.Column('hobby', sa.Enum('LISTENING_TO_MUSIC', 'SINGING', 'PLAYING_GUITAR', 'RUNNING', 'YOGA', 'READING', 'COOKING', 'PHOTOGRAPHY', 'TRAVELING', 'VIDEO_GAMES', 'DOG_LOVER', 'MEDITATION', 'FASHION', 'BLOGGING', name='hobbyenum'), nullable=True))
    op.alter_column(
    'profiles',
    'gender',
    existing_type=sa.VARCHAR(),
    type_=sa.Enum('MALE', 'FEMALE', name='genderenum'),
    existing_nullable=False,
    postgresql_using="gender::genderenum"
)
    op.drop_constraint('profiles_email_key', 'profiles', type_='unique')
    op.drop_constraint('profiles_username_key', 'profiles', type_='unique')
    op.create_unique_constraint(None, 'profiles', ['last_name'])
    op.create_unique_constraint(None, 'profiles', ['first_name'])
    op.drop_column('profiles', 'username')
    op.drop_column('profiles', 'email')
    op.drop_column('profiles', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('profiles', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_constraint(None, 'profiles', type_='unique')
    op.create_unique_constraint('profiles_username_key', 'profiles', ['username'])
    op.create_unique_constraint('profiles_email_key', 'profiles', ['email'])
    op.alter_column('profiles', 'gender',
               existing_type=sa.Enum('MALE', 'FEMALE', name='genderenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('profiles', 'hobby')
    op.drop_column('profiles', 'last_name')
    op.drop_column('profiles', 'first_name')
    op.create_table('demo-table',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='demo-table_pkey')
    )
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('salary', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_activate', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='employees_pkey'),
    sa.UniqueConstraint('email', name='employees_email_key')
    )
    # ### end Alembic commands ###
